version: "3.9"
services:
    api:
        build: .
        depends_on:
            - mongo
        environment:
            NODE_ENV: development
            PORT: 9000
            MONGO_URL: mongodb://mongo:27017/db
            JWT_SECRET: "some_secure_tkn"
        ports:
            - "9000:9000"
        volumes:
            - ./:/app
    mongo:
        image: mongo
        ports:
            - "27017:27017"